basePath: /api/v1/
definitions:
  request.BuyStoreRequest:
    properties:
      productId:
        type: string
      token:
        type: string
    type: object
  request.EmailRequest:
    properties:
      user:
        properties:
          email:
            type: string
        required:
        - email
        type: object
    type: object
  request.LoginRequest:
    properties:
      user:
        properties:
          email:
            type: string
          password:
            type: string
        type: object
    type: object
  request.OtpRequest:
    properties:
      email:
        type: string
      otp:
        type: integer
    required:
    - email
    - otp
    type: object
  request.PlayerLevelRewardCollectRequest:
    properties:
      level:
        type: integer
    type: object
  request.RestPasswordRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.SigupRequest:
    properties:
      user:
        properties:
          avatar:
            type: integer
          email:
            type: string
          password:
            type: string
          username:
            type: string
        type: object
    type: object
  request.SocialLoginReq:
    properties:
      avatar:
        type: integer
      email:
        type: string
      uid:
        type: string
    type: object
  request.UpdatePlayer:
    properties:
      avatar:
        type: integer
      username:
        type: string
    type: object
  response.Status:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  response.Success:
    properties:
      status:
        $ref: '#/definitions/response.Status'
    type: object
info:
  contact: {}
  description: This is the api documentation of survival party game
  title: Survival Party
  version: "1.0"
paths:
  /buy-store:
    post:
      consumes:
      - application/json
      description: Buy the assests from the shop
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: shop Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.BuyStoreRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Sucess
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Buy things
      tags:
      - Store
  /check-otp:
    post:
      consumes:
      - application/json
      description: Verifies the otp sent on email
      parameters:
      - description: Email Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.OtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Verifies OTP
      tags:
      - Authentication
  /get-daily-goals:
    get:
      consumes:
      - application/json
      description: Gets the daily goals for given player
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucess
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Get the daily goals
      tags:
      - DailyGoal
  /get-level-rewards:
    get:
      consumes:
      - application/json
      description: Gets the rewards according to player level
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Gets reward list
      tags:
      - Player
  /get-settings:
    get:
      consumes:
      - application/json
      description: Gets the current settings of that player
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucess
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Gets the settings
      tags:
      - Player
  /level-reward-collect:
    post:
      consumes:
      - application/json
      description: Collects the reward for a level of that player
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Player Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.PlayerLevelRewardCollectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Collects Reward
      tags:
      - Player
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 72e6077 (doc:created docs for routes)
=======
=======
>>>>>>> c4acd51 (feat: added pop up offer route)
>>>>>>> 7b19332 (feat: added pop up offer route)
=======
=======
>>>>>>> c4acd51 (feat: added pop up offer route)
=======
>>>>>>> 9b94616 (resolved merge conflicts)
>>>>>>> 52d6069 (resolved merge conflicts)
=======
>>>>>>> 2446eb2 (fixed minor issues)
  /popupoffers:
    get:
      consumes:
      - application/json
      description: Get the specific type of reward
      parameters:
      - description: Type of reward
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorised
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Get the specific type of reward
      tags:
      - Store
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> 7b19332 (feat: added pop up offer route)
=======
>>>>>>> 52d6069 (resolved merge conflicts)
=======
>>>>>>> a459c37 (doc:created docs for routes)
=======
>>>>>>> 14d0086 (doc:created docs for routes)
<<<<<<< HEAD
>>>>>>> 72e6077 (doc:created docs for routes)
=======
=======
>>>>>>> c4acd51 (feat: added pop up offer route)
<<<<<<< HEAD
>>>>>>> 7b19332 (feat: added pop up offer route)
=======
=======
>>>>>>> 9b94616 (resolved merge conflicts)
>>>>>>> 52d6069 (resolved merge conflicts)
=======
>>>>>>> 2446eb2 (fixed minor issues)
  /reset-password:
    post:
      consumes:
      - application/json
      description: Resets the password of the user
      parameters:
      - description: Email Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.RestPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Resets the password
      tags:
      - Authentication
  /send-otp:
    post:
      consumes:
      - application/json
      description: Sends the otp on the register email
      parameters:
      - description: Email Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.EmailRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Sends OTP
      tags:
      - Authentication
  /stats:
    get:
      consumes:
      - application/json
      description: Get the player game stats
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Get player game stats
      tags:
      - Player
  /store:
    get:
      consumes:
      - application/json
      description: Gets shop details
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Sucess
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Gets shop details
      tags:
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
      - Store
=======
<<<<<<< HEAD
>>>>>>> 5caa952 (resolved merge conflicts)
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<< HEAD
      - Player
>>>>>>> a459c37 (doc:created docs for routes)
  /update_settings:
=======
=======
>>>>>>> 9b94616 (resolved merge conflicts)
=======
>>>>>>> 2446eb2 (fixed minor issues)
      - Store
>>>>>>> 52d6069 (resolved merge conflicts)
  /update-settings:
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> a1e10ba (feat: daily goals)
=======
      - Player
  /update_settings:
>>>>>>> 14d0086 (doc:created docs for routes)
<<<<<<< HEAD
=======
=======
>>>>>>> 46c96ed (feat: daily goals)
=======
>>>>>>> 9b94616 (resolved merge conflicts)
>>>>>>> 5caa952 (resolved merge conflicts)
=======
>>>>>>> 0027c48 (fixed minor issues)
    put:
      consumes:
      - application/json
      description: Updates the game settings of that player
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Player Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.PlayerLevelRewardCollectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Sucess
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Updates setting
      tags:
      - Player
  /user-data:
    put:
      consumes:
      - application/json
      description: Updates player info like username and avatar
      parameters:
      - description: Player Access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Player Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.UpdatePlayer'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Updates player info
      tags:
      - Player
  /users/email-verify:
    get:
      consumes:
      - application/json
      description: Perform Email verifictaion
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: User email verification
      tags:
      - Authentication
  /users/sign-in:
    post:
      consumes:
      - application/json
      description: Perform Users login and generate access token
      parameters:
      - description: Login Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: User Login
      tags:
      - Authentication
<<<<<<< HEAD
<<<<<<< HEAD
  /users/sign-out:
=======
  /users/sign_out:
>>>>>>> 686f25b (feat: daily goals)
=======
  /users/sign-out:
>>>>>>> 52d6069 (resolved merge conflicts)
    delete:
      consumes:
      - application/json
      description: Logs out a player
      parameters:
      - description: Player Access Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Success'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Success'
      summary: Logout Player
      tags:
      - Authentication
  /users/sign-up:
    post:
      consumes:
      - application/json
      description: Perform signup and sends email for verification
      parameters:
      - description: Signup Request
        in: body
        name: guestLoginRequest
        required: true
        schema:
          $ref: '#/definitions/request.SigupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: Sign Up
      tags:
      - Authentication
  /users/social-login:
    post:
      consumes:
      - application/json
      description: Perform Users social login and generate access token
      parameters:
      - description: Login Details
        in: body
        name: loginDetails
        required: true
        schema:
          $ref: '#/definitions/request.SocialLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: Login successful
          schema:
            $ref: '#/definitions/response.Success'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/response.Success'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Success'
      summary: User Login
      tags:
      - Authentication
swagger: "2.0"
